//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almacen02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Despacho
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public string tipo_de_acciom { get; set; }
        public int cliente { get; set; }
        public string contactos { get; set; }
        public int Detalle_de_productos { get; set; }
        public Nullable<decimal> cant_producto { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual producto producto { get; set; }
    }
}
